"""Added is_admin field to User table

Revision ID: 10465fdd7a13
Revises: 29ad924a9eca
Create Date: 2024-12-23 23:51:30.328949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10465fdd7a13'
down_revision = '29ad924a9eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
    # Удалить server_default после применения миграции
    op.alter_column('user', 'is_admin', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
