"""Added documents field to VisaApplication

Revision ID: 29ad924a9eca
Revises: 2c79d907c444
Create Date: 2024-12-23 22:52:44.112724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ad924a9eca'
down_revision = '2c79d907c444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documents', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa_application', schema=None) as batch_op:
        batch_op.drop_column('documents')

    # ### end Alembic commands ###
