"""Add visa info and country models

Revision ID: 3c4678bd603a
Revises: 9b53b20fbaff
Create Date: 2024-12-23 02:47:56.471550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4678bd603a'
down_revision = '9b53b20fbaff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('visa_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('visa_type', sa.String(length=100), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('processing_time', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('vaccinations', sa.Text(), nullable=True),
    sa.Column('useful_links', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visa_info')
    op.drop_table('country')
    # ### end Alembic commands ###
