"""Add otp_secret to User

Revision ID: 714fa1968a11
Revises: f3c55f00664c
Create Date: 2024-12-22 16:38:26.984745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714fa1968a11'
down_revision = 'f3c55f00664c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=16), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###
