"""visa field schema

Revision ID: 99818d474a22
Revises: ec648a70d51e
Create Date: 2025-04-28 20:26:12.279940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99818d474a22'
down_revision = 'ec648a70d51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('visa_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa_info', schema=None) as batch_op:
        batch_op.drop_column('additional_fields')

    with op.batch_alter_table('visa_application', schema=None) as batch_op:
        batch_op.drop_column('extra_data')

    # ### end Alembic commands ###
