"""Remove otp_secret from User

Revision ID: 9b53b20fbaff
Revises: 714fa1968a11
Create Date: 2024-12-22 18:10:55.965436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b53b20fbaff'
down_revision = '714fa1968a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.VARCHAR(length=16), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
