"""Add description field to Country

Revision ID: b6346fcdff09
Revises: f9d8d467ec69
Create Date: 2025-04-15 01:50:38.878633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6346fcdff09'
down_revision = 'f9d8d467ec69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
